apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: acceleratedworker1g
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,worker1g]}
  maxUnavailable: "10%"
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker1g: ""
